
name: integration

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: |
          npm install @commitlint/{config-conventional,cli}
      
      - name: Validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate all commits from PR
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.21'
          - '1.22'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56

      - name: Test with Go
        run: go test -v
